{
    "swagger": "2.0",
    "info": {
      "contact": {},
      "title": "CyberArk AD Connector",
      "version": "1.0",
      "x-applicationinfo": {
        "x-API-Description": "The CyberArk Identity Flows AD Connector allows connectivity to on-premise Active Directory for user and group management functions.",
        "x-API-Documentation-URL": "https://identity-developer.cyberark.com/reference",
        "x-API-Name": "CyberArk AD Connector",
        "x-App-Categories": [],
        "x-App-Description": "Secure access across any device, anywhere, at just the right time with the most complete and flexible set of Identity Security capabilities.",
        "x-App-Logo": "https://flows-images.s3.amazonaws.com/cyberark.png",
        "x-App-Name": "Identity Security Platform",
        "x-App-URL": "https://www.cyberark.com/",
        "x-Category": "",
        "x-Company": "CyberArk",
        "x-Company-Github": "https://github.com/cyberark",
        "x-Orig-Desc-Format": "JSON",
        "x-Orig-Desc-Type": "OpenAPI 2.0",
        "x-additionalHostNames": ""
      }
    },
    "securityDefinitions": {},
    "host": "coffeecache.my.idaptive.app",
    "basePath": "/",
    "schemes": [
      "https"
    ],
    "consumes": [
      "application/json"
    ],
    "produces": [
      "application/json"
    ],
    "paths": {
      "/entity/assigngroups": {
        "post": {
          "consumes": [
            "application/json"
          ],
          "deprecated": false,
          "description": "assign group",
          "operationId": "assign group",
          "parameters": [
            {
              "description": "",
              "enum": [
                "application/json"
              ],
              "in": "header",
              "name": "Content-Type",
              "required": false,
              "type": "string"
            },
            {
              "description": "",
              "example": {
                "ContainerDn": "CN=Users,DC=CLOUDDEV,DC=TEST",
                "DirectoryId": "{{directory}}",
                "Domain": "CLOUDDEV.TEST",
                "GroupIds": [
                  "4ee2876e-224c-4f3b-8b65-25640aaab802"
                ],
                "Server": "CLOUD-DC-VM.CLOUDDEV.TEST",
                "UserId": "05a9e2a7-206d-4ada-ad1a-f7240a472af8"
              },
              "in": "body",
              "name": "body",
              "required": false,
              "schema": {
                "properties": {
                  "ContainerDn": {
                    "type": "string"
                  },
                  "DirectoryId": {
                    "type": "string"
                  },
                  "Domain": {
                    "type": "string"
                  },
                  "GroupIds": {
                    "items": {
                      "type": "string"
                    },
                    "type": "array"
                  },
                  "Server": {
                    "type": "string"
                  },
                  "UserId": {
                    "type": "string"
                  }
                },
                "type": "object"
              }
            }
          ],
          "produces": [
            "application/json"
          ],
          "responses": {
            "200": {
              "description": "success",
              "schema": {
                "$ref": "#/definitions/assignGroups"
              }
            }
          },
          "summary": "assign groups",
          "tags": [
            "Groups"
          ]
        }
      },
      "/entity/changepassword": {
        "post": {
          "consumes": [
            "application/json"
          ],
          "deprecated": false,
          "description": "change password",
          "operationId": "changePassword",
          "parameters": [
            {
              "description": "",
              "in": "header",
              "name": "X-IDAP-NATIVE-CLIENT",
              "required": false,
              "type": "string"
            },
            {
              "description": "",
              "enum": [
                "application/json"
              ],
              "in": "header",
              "name": "Content-Type",
              "required": false,
              "type": "string"
            },
            {
              "description": "",
              "in": "body",
              "name": "body",
              "required": false,
              "schema": {
                "$ref": "#/definitions/EntityChangepasswordRequest"
              }
            }
          ],
          "produces": [
            "application/json"
          ],
          "responses": {
            "200": {
              "description": "success",
              "schema": {
                "$ref": "#/definitions/ResetPasswordResponse"
              }
            }
          },
          "summary": "changePassword",
          "tags": [
            "Users"
          ]
        }
      },
      "/entity/createuser": {
        "post": {
          "consumes": [
            "application/json"
          ],
          "deprecated": false,
          "description": "create user",
          "operationId": "createUser",
          "parameters": [
            {
              "description": "",
              "in": "header",
              "name": "X-IDAP-NATIVE-CLIENT",
              "required": false,
              "type": "string"
            },
            {
              "description": "",
              "enum": [
                "application/json"
              ],
              "in": "header",
              "name": "Content-Type",
              "required": false,
              "type": "string"
            },
            {
              "description": "",
              "in": "body",
              "name": "body",
              "required": false,
              "schema": {
                "$ref": "#/definitions/EntityCreateuserRequest"
              }
            }
          ],
          "produces": [
            "application/json"
          ],
          "responses": {
            "200": {
              "description": "success",
              "examples": {
                "application/json": {
                  "ErrorCode": null,
                  "ErrorID": null,
                  "Exception": null,
                  "InnerExceptions": null,
                  "IsSoftError": false,
                  "Message": null,
                  "MessageID": null,
                  "Result": {
                    "ADUserId": "a66567e4-3b80-4201-a96a-3e8ff6cf5154",
                    "ChangedProperties": [
                      {
                        "NewValues": [
                          "Justine.Doe@cstest.cache.coffee"
                        ],
                        "OldValues": null,
                        "PropertyName": "userprincipalname"
                      },
                      {
                        "NewValues": [
                          "C00395"
                        ],
                        "OldValues": null,
                        "PropertyName": "samaccountname"
                      },
                      {
                        "NewValues": [
                          "Justine"
                        ],
                        "OldValues": null,
                        "PropertyName": "givenName"
                      },
                      {
                        "NewValues": [
                          "Justine Doe"
                        ],
                        "OldValues": null,
                        "PropertyName": "cn"
                      },
                      {
                        "NewValues": [
                          "Doe"
                        ],
                        "OldValues": null,
                        "PropertyName": "sn"
                      }
                    ],
                    "ErrorMessage": null,
                    "ExceptionString": null,
                    "MemberOfAllGroups": [],
                    "PasswordNeedToBeChanged": true,
                    "RequestId": "89ce43c5ae8e4cdcb1c9078681a2fbeb",
                    "Status": 0,
                    "Substatus": 0,
                    "TempPasswordSet": true,
                    "UserAccountControlAction": 0,
                    "UserDn": "CN=Justine Doe,OU=Artists In Residence,DC=aa,DC=local"
                  },
                  "success": true
                }
              },
              "headers-example": {
                "Status": 200
              },
              "schema": {
                "$ref": "#/definitions/CreateUserResponse"
              }
            }
          },
          "summary": "createUser",
          "tags": [
            "Users"
          ]
        }
      },
      "/entity/deleteuser": {
        "post": {
          "consumes": [
            "application/json"
          ],
          "deprecated": false,
          "description": "delete user",
          "operationId": "deleteUser",
          "parameters": [
            {
              "description": "",
              "in": "header",
              "name": "X-IDAP-NATIVE-CLIENT",
              "required": false,
              "type": "string"
            },
            {
              "description": "",
              "enum": [
                "application/json"
              ],
              "in": "header",
              "name": "Content-Type",
              "required": false,
              "type": "string"
            },
            {
              "description": "",
              "in": "body",
              "name": "body",
              "required": false,
              "schema": {
                "$ref": "#/definitions/EntityDeleteuserRequest"
              }
            }
          ],
          "produces": [
            "application/json"
          ],
          "responses": {
            "200": {
              "description": "success",
              "schema": {
                "$ref": "#/definitions/DeleteUserResponse"
              }
            }
          },
          "summary": "deleteUser",
          "tags": [
            "Users"
          ]
        }
      },
      "/entity/getdirectories": {
        "get": {
          "deprecated": false,
          "description": "get directories",
          "operationId": "getDirectories",
          "parameters": [
            {
              "description": "",
              "in": "header",
              "name": "X-IDAP-NATIVE-CLIENT",
              "required": false,
              "type": "string"
            }
          ],
          "produces": [
            "application/json"
          ],
          "responses": {
            "200": {
              "description": "success",
              "examples": {
                "application/json": {
                  "ErrorCode": null,
                  "ErrorID": null,
                  "Exception": null,
                  "InnerExceptions": null,
                  "IsSoftError": false,
                  "Message": null,
                  "MessageID": null,
                  "Result": [
                    {
                      "Name": "AdProxy_symbotictest.corp",
                      "ServiceName": "AdProxy",
                      "Uuid": "3dd4d9b7-b111-07b0-910d-94c2b5f6d244"
                    }
                  ],
                  "success": true
                }
              },
              "schema": {
                "$ref": "#/definitions/GetDirectoriesResponse"
              }
            }
          },
          "summary": "getDirectories",
          "tags": [
            "Directory Queries"
          ]
        }
      },
      "/entity/ldapquery": {
        "post": {
          "consumes": [
            "application/json"
          ],
          "deprecated": false,
          "description": "search query",
          "operationId": "searchQuery",
          "parameters": [
            {
              "description": "",
              "in": "header",
              "name": "X-IDAP-NATIVE-CLIENT",
              "required": false,
              "type": "string"
            },
            {
              "description": "",
              "enum": [
                "application/json"
              ],
              "in": "header",
              "name": "Content-Type",
              "required": false,
              "type": "string"
            },
            {
              "description": "",
              "in": "body",
              "name": "body",
              "required": false,
              "schema": {
                "$ref": "#/definitions/EntityLdapqueryRequest"
              }
            }
          ],
          "produces": [
            "application/json"
          ],
          "responses": {
            "200": {
              "description": "success",
              "examples": {
                "application/json": {
                  "ErrorCode": null,
                  "ErrorID": null,
                  "Exception": null,
                  "InnerExceptions": null,
                  "IsSoftError": false,
                  "Message": null,
                  "MessageID": null,
                  "Result": [
                    {
                      "DirectoryServiceUuid": "82d7d4ac-1556-852a-c305-863007f6ed41",
                      "m_directory": {
                        "DirectoryServiceUuid": "82d7d4ac-1556-852a-c305-863007f6ed41",
                        "m_forest": "cc.local",
                        "m_tenantId": "AAM4903"
                      },
                      "m_effGroupUuids": null,
                      "m_entry": {
                        "Children": [],
                        "ForestName": "cc.local",
                        "Guid": "3c710c59-7693-4399-a82d-04223ca04ec1",
                        "Name": null,
                        "NetBiosDomainName": "CCLocal",
                        "Path": "GC://WIN-SR7E6F6L25U.cc.local/CN=Arabica Bean,OU=Beans,DC=cc,DC=local",
                        "Properties": {
                          "ObjectType": [
                            "User"
                          ],
                          "cn": [
                            "Arabica Bean"
                          ],
                          "company": [],
                          "department": [
                            "Beans Of The World"
                          ],
                          "distinguishedname": [
                            "CN=Arabica Bean,OU=Beans,DC=cc,DC=local"
                          ],
                          "employeeid": [
                            "424242"
                          ],
                          "employeetype": [
                            "FT"
                          ],
                          "mail": [
                            "arabica@localad.cache.coffee"
                          ],
                          "manager": [
                            "CN=kcreason,CN=Users,DC=cc,DC=local"
                          ],
                          "memberof": [
                            "CN=CAI-365-Group-NoVA-email,OU=Groups,DC=cc,DC=local",
                            "CN=CAI-365-Group-Virginia,OU=Groups,DC=cc,DC=local",
                            "CN=CAI-365-GroupForSharepoint,OU=Groups,DC=cc,DC=local",
                            "CN=universal-distro,OU=Groups for Azure Sync,DC=cc,DC=local",
                            "CN=universal-security,OU=Groups for Azure Sync,DC=cc,DC=local",
                            "CN=global-distro,OU=Groups for Azure Sync,DC=cc,DC=local",
                            "CN=global-security,OU=Groups for Azure Sync,DC=cc,DC=local",
                            "CN=domain-local-distro,OU=Groups for Azure Sync,DC=cc,DC=local",
                            "CN=Domain-local-security,OU=Groups for Azure Sync,DC=cc,DC=local",
                            "CN=Bean Management,OU=Groups,DC=cc,DC=local",
                            "CN=Not_For_cloud,CN=Builtin,DC=cc,DC=local",
                            "CN=365 User,OU=Groups,DC=cc,DC=local",
                            "CN=Favorite Beans,OU=Groups,DC=cc,DC=local",
                            "CN=CyberArk-GSec for provisioning use,OU=Groups,DC=cc,DC=local",
                            "CN=Universal Distribution Group,OU=Distribution Groups,OU=Groups,DC=cc,DC=local",
                            "CN=Global Distribution Group,OU=Distribution Groups,OU=Groups,DC=cc,DC=local",
                            "CN=Domain Local Distribution Group,OU=Distribution Groups,OU=Groups,DC=cc,DC=local",
                            "CN=Domain Local Security Group,OU=Groups,DC=cc,DC=local"
                          ],
                          "msds-parentdistname": [
                            "OU=Beans,DC=cc,DC=local"
                          ],
                          "physicaldeliveryofficename": [],
                          "samaccountname": [
                            "arabica"
                          ],
                          "title": [],
                          "useraccountcontrol": [
                            "512"
                          ],
                          "userprincipalname": [
                            "arabica@localad.cache.coffee"
                          ]
                        },
                        "SchemaClasses": []
                      },
                      "m_groupUuids": null,
                      "m_tenantId": "AAM4903"
                    }
                  ],
                  "success": true
                }
              },
              "headers-example": {
                "status": 200
              },
              "schema": {
                "$ref": "#/definitions/LdapQueryResponse"
              }
            }
          },
          "summary": "searchQuery",
          "tags": [
            "Directory Queries"
          ]
        }
      },
      "/entity/resetpassword": {
        "post": {
          "consumes": [
            "application/json"
          ],
          "deprecated": false,
          "description": "reset password",
          "operationId": "resetPassword",
          "parameters": [
            {
              "description": "",
              "in": "header",
              "name": "X-IDAP-NATIVE-CLIENT",
              "required": false,
              "type": "string"
            },
            {
              "description": "",
              "enum": [
                "application/json"
              ],
              "in": "header",
              "name": "Content-Type",
              "required": false,
              "type": "string"
            },
            {
              "description": "",
              "in": "body",
              "name": "body",
              "required": false,
              "schema": {
                "$ref": "#/definitions/EntityResetpasswordRequest"
              }
            }
          ],
          "produces": [
            "application/json"
          ],
          "responses": {
            "200": {
              "description": "success",
              "schema": {
                "$ref": "#/definitions/ResetPasswordResponse"
              }
            }
          },
          "summary": "resetPassword",
          "tags": [
            "Users"
          ]
        }
      },
      "/entity/unassigngroups": {
        "post": {
          "consumes": [
            "application/json"
          ],
          "deprecated": false,
          "description": "unassign group",
          "operationId": "unassign group",
          "parameters": [
            {
              "description": "",
              "enum": [
                "application/json"
              ],
              "in": "header",
              "name": "Content-Type",
              "required": false,
              "type": "string"
            },
            {
              "description": "",
              "example": {
                "ContainerDn": "CN=Users,DC=CLOUDDEV,DC=TEST",
                "DirectoryId": "{{directory}}",
                "Domain": "CLOUDDEV.TEST",
                "GroupIds": [
                  "4ee2876e-224c-4f3b-8b65-25640aaab802"
                ],
                "Server": "CLOUD-DC-VM.CLOUDDEV.TEST",
                "UserId": "05a9e2a7-206d-4ada-ad1a-f7240a472af8"
              },
              "in": "body",
              "name": "body",
              "required": false,
              "schema": {
                "properties": {
                  "ContainerDn": {
                    "type": "string"
                  },
                  "DirectoryId": {
                    "type": "string"
                  },
                  "Domain": {
                    "type": "string"
                  },
                  "GroupIds": {
                    "items": {
                      "type": "string"
                    },
                    "type": "array"
                  },
                  "Server": {
                    "type": "string"
                  },
                  "UserId": {
                    "type": "string"
                  }
                },
                "type": "object"
              }
            }
          ],
          "produces": [
            "application/json"
          ],
          "responses": {
            "200": {
              "description": "success",
              "schema": {
                "$ref": "#/definitions/unassignGroups"
              }
            }
          },
          "summary": "unassign groups",
          "tags": [
            "Groups"
          ]
        }
      },
      "/entity/updateuser": {
        "post": {
          "consumes": [
            "application/json"
          ],
          "deprecated": false,
          "description": "update user",
          "operationId": "updateUser",
          "parameters": [
            {
              "description": "",
              "in": "header",
              "name": "X-IDAP-NATIVE-CLIENT",
              "required": false,
              "type": "string"
            },
            {
              "description": "",
              "enum": [
                "application/json"
              ],
              "in": "header",
              "name": "Content-Type",
              "required": false,
              "type": "string"
            },
            {
              "description": "",
              "in": "body",
              "name": "body",
              "required": false,
              "schema": {
                "$ref": "#/definitions/EntityUpdateuserRequest"
              }
            }
          ],
          "produces": [
            "application/json"
          ],
          "responses": {
            "200": {
              "description": "success",
              "schema": {
                "$ref": "#/definitions/UpdateUserResponse"
              }
            }
          },
          "summary": "updateUser",
          "tags": [
            "Users"
          ]
        }
      },
      "/entity/validatepassword": {
        "post": {
          "consumes": [
            "application/json"
          ],
          "deprecated": false,
          "description": "validate password",
          "operationId": "validatePassword",
          "parameters": [
            {
              "description": "",
              "in": "header",
              "name": "X-IDAP-NATIVE-CLIENT",
              "required": false,
              "type": "string"
            },
            {
              "description": "",
              "enum": [
                "application/json"
              ],
              "in": "header",
              "name": "Content-Type",
              "required": false,
              "type": "string"
            },
            {
              "description": "",
              "in": "body",
              "name": "body",
              "required": false,
              "schema": {
                "$ref": "#/definitions/EntityValidatepasswordRequest"
              }
            }
          ],
          "produces": [
            "application/json"
          ],
          "responses": {
            "200": {
              "description": "success",
              "schema": {
                "$ref": "#/definitions/ValidatePasswordResponse"
              }
            }
          },
          "summary": "validatePassword",
          "tags": [
            "Users"
          ]
        }
      }
    },
    "parameters": {},
    "definitions": {
      "CreateUserResponse": {
        "properties": {
          "ErrorCode": {
            "example": null,
            "type": "string"
          },
          "ErrorID": {
            "example": null,
            "type": "string"
          },
          "Exception": {
            "example": null,
            "type": "string"
          },
          "InnerExceptions": {
            "example": null,
            "type": "string"
          },
          "IsSoftError": {
            "example": false,
            "type": "boolean"
          },
          "Message": {
            "example": null,
            "type": "string"
          },
          "MessageID": {
            "example": null,
            "type": "string"
          },
          "Result": {
            "example": {
              "ADUserId": "eecbcd1b-7905-4242-8250-7a63e6a4d1c7",
              "ChangedProperties": [
                {
                  "NewValues": [
                    "testuser2@CLOUDDEV.TEST"
                  ],
                  "OldValues": null,
                  "PropertyName": "userprincipalname"
                }
              ],
              "ErrorMessage": null,
              "ExceptionString": null,
              "MemberOfAllGroups": [
                null
              ],
              "PasswordNeedToBeChanged": true,
              "RequestId": "3c818e399a18402096864c055f1982d7",
              "Status": 0,
              "Substatus": 0,
              "TempPasswordSet": true,
              "UserAccountControlAction": 0,
              "UserDn": "CN=testUser2,CN=Users,DC=CLOUDDEV,DC=TEST\""
            },
            "type": "object"
          },
          "success": {
            "example": true,
            "type": "boolean"
          }
        },
        "type": "object"
      },
      "DeleteUserResponse": {
        "properties": {
          "ErrorCode": {
            "example": null,
            "type": "string"
          },
          "ErrorID": {
            "example": null,
            "type": "string"
          },
          "Exception": {
            "example": null,
            "type": "string"
          },
          "InnerExceptions": {
            "example": null,
            "type": "string"
          },
          "IsSoftError": {
            "example": false,
            "type": "boolean"
          },
          "Message": {
            "example": null,
            "type": "string"
          },
          "MessageID": {
            "example": null,
            "type": "string"
          },
          "Result": {
            "example": {
              "ADUserId": "eecbcd1b-7905-4242-8250-7a63e6a4d1c7",
              "ChangedProperties": [
                null
              ],
              "ErrorMessage": null,
              "ExceptionString": null,
              "MemberOfAllGroups": [
                null
              ],
              "PasswordNeedToBeChanged": false,
              "RequestId": "3c818e399a18402096864c055f1982d7",
              "Status": 0,
              "Substatus": 2,
              "TempPasswordSet": false,
              "UserAccountControlAction": 0,
              "UserDn": "CN=testUser2,CN=Users,DC=CLOUDDEV,DC=TEST\""
            },
            "type": "object"
          },
          "success": {
            "example": true,
            "type": "boolean"
          }
        },
        "type": "object"
      },
      "EntityChangepasswordRequest": {
        "properties": {
          "NewPassword": {
            "example": "testTEST12345",
            "type": "string"
          },
          "OldPassword": {
            "example": "testTEST1234",
            "type": "string"
          },
          "UserId": {
            "example": "05a9e2a7-206d-4ada-ad1a-f7240a472af8",
            "type": "string"
          }
        },
        "title": "EntityChangepasswordRequest",
        "type": "object"
      },
      "EntityCreateuserRequest": {
        "properties": {
          "ContainerDn": {
            "example": "CN=Users,DC=CLOUDDEV,DC=TEST",
            "type": "string"
          },
          "DirectoryId": {
            "example": "00e81d5d-19e2-212d-4ac4-19b32024e729",
            "type": "string"
          },
          "Disabled": {
            "example": "true",
            "type": "string"
          },
          "Domain": {
            "example": "CLOUDDEV.TEST",
            "type": "string"
          },
          "Server": {
            "example": "CLOUD-DC-VM.CLOUDDEV.TEST",
            "type": "string"
          },
          "Username": {
            "example": "testUser19",
            "type": "string"
          },
          "cn": {
            "example": "testUser19",
            "type": "string"
          },
          "givenName": {
            "example": "Frank",
            "type": "string"
          },
          "samaccountname": {
            "example": "testUser19",
            "type": "string"
          },
          "sn": {
            "example": "Test",
            "type": "string"
          },
          "userprincipalname": {
            "example": "testUser19@clouddev.test",
            "type": "string"
          }
        },
        "title": "EntityCreateuserRequest",
        "type": "object"
      },
      "EntityDeleteuserRequest": {
        "properties": {
          "ContainerDn": {
            "example": "CN=Users,DC=CLOUDDEV,DC=TEST",
            "type": "string"
          },
          "DirectoryId": {
            "example": "00e81d5d-19e2-212d-4ac4-19b32024e729",
            "type": "string"
          },
          "Domain": {
            "example": "CLOUDDEV.TEST",
            "type": "string"
          },
          "Server": {
            "example": "CLOUD-DC-VM.CLOUDDEV.TEST",
            "type": "string"
          },
          "UserId": {
            "example": "252c1f2f-0798-4fab-8d1e-376bd7f4a6d0",
            "type": "string"
          }
        },
        "title": "EntityDeleteuserRequest",
        "type": "object"
      },
      "EntityLdapqueryRequest": {
        "properties": {
          "Attributes": {
            "example": [
              "samaccountname",
              "mycustomattribute1",
              "postalCode",
              "sn"
            ],
            "items": {
              "type": "string"
            },
            "type": "array"
          },
          "DirectoryId": {
            "example": "00e81d5d-19e2-212d-4ac4-19b32024e729",
            "type": "string"
          },
          "Query": {
            "example": "(&(objectClass=user)(&(|(|(|(|(displayname=admin*)(givenName=admin*))(sn=admin*))(|(sAMAccountName=test*)(userPrincipalName=tuser*))))(objectCategory=user)))",
            "type": "string"
          }
        },
        "title": "EntityLdapqueryRequest",
        "type": "object"
      },
      "EntityResetpasswordRequest": {
        "properties": {
          "NewPassword": {
            "example": "testTEST1234",
            "type": "string"
          },
          "UserId": {
            "example": "05a9e2a7-206d-4ada-ad1a-f7240a472af8",
            "type": "string"
          }
        },
        "title": "EntityResetpasswordRequest",
        "type": "object"
      },
      "EntityUpdateuserRequest": {
        "properties": {
          "ContainerDn": {
            "example": "CN=Users,DC=CLOUDDEV,DC=TEST",
            "type": "string"
          },
          "DirectoryId": {
            "example": "00e81d5d-19e2-212d-4ac4-19b32024e729",
            "type": "string"
          },
          "Domain": {
            "example": "CLOUDDEV.TEST",
            "type": "string"
          },
          "Server": {
            "example": "CLOUD-DC-VM.CLOUDDEV.TEST",
            "type": "string"
          },
          "UserId": {
            "example": "accf721c-616c-4e4f-932c-7901b97306cd",
            "type": "string"
          },
          "givenName": {
            "example": "Frank",
            "type": "string"
          },
          "sn": {
            "example": "Test2",
            "type": "string"
          }
        },
        "title": "EntityUpdateuserRequest",
        "type": "object"
      },
      "EntityValidatepasswordRequest": {
        "properties": {
          "Password": {
            "example": "testTEST1234",
            "type": "string"
          },
          "Username": {
            "example": "testUser19",
            "type": "string"
          }
        },
        "title": "EntityValidatepasswordRequest",
        "type": "object"
      },
      "GetDirectoriesResponse": {
        "properties": {
          "ErrorCode": {
            "example": null,
            "type": "string"
          },
          "ErrorID": {
            "example": null,
            "type": "string"
          },
          "Exception": {
            "example": null,
            "type": "string"
          },
          "InnerExceptions": {
            "example": null,
            "type": "string"
          },
          "IsSoftError": {
            "example": false,
            "type": "boolean"
          },
          "Message": {
            "example": null,
            "type": "string"
          },
          "MessageID": {
            "example": null,
            "type": "string"
          },
          "Result": {
            "example": [
              {
                "Name": "AdProxy_CLOUDDEV.TEST",
                "ServiceName": "AdProxy",
                "Uuid": "00e81d5d-19e2-212d-4ac4-19b32024e729"
              }
            ],
            "items": {},
            "type": "array"
          },
          "success": {
            "example": true,
            "type": "boolean"
          }
        },
        "type": "object"
      },
      "LdapQueryResponse": {
        "properties": {
          "ErrorCode": {
            "example": null,
            "type": "string"
          },
          "ErrorID": {
            "example": null,
            "type": "string"
          },
          "Exception": {
            "example": null,
            "type": "string"
          },
          "InnerExceptions": {
            "example": null,
            "type": "string"
          },
          "IsSoftError": {
            "example": false,
            "type": "boolean"
          },
          "Message": {
            "example": null,
            "type": "string"
          },
          "MessageID": {
            "example": null,
            "type": "string"
          },
          "Result": {
            "example": [
              {
                "DirectoryServiceUuid": "00e81d5d-19e2-212d-4ac4-19b32024e729",
                "m_directory": {
                  "DirectoryServiceUuid": "00e81d5d-19e2-212d-4ac4-19b32024e729",
                  "m_forest": "CLOUDDEV.TEST",
                  "m_tenantId": "ABC0123"
                },
                "m_effGroupUuids": null,
                "m_entry": {
                  "ForestName": "CLOUDDEV.TEST",
                  "Guid": "c70d194a-7f80-4ce9-908a-7c537486127b",
                  "Name": null,
                  "NetBiosDomainName": "CLOUDDEV",
                  "Path": "GC://WIN.CLOUDDEV.TEST/CN=Administrator,CN=Users,DC=CLOUDDEV,DC=TEST",
                  "Properties": {
                    "Children": [
                      null
                    ],
                    "ObjectType": [
                      "User"
                    ],
                    "samaccountname": [
                      "Administrator"
                    ]
                  },
                  "SchemaClasses": [
                    null
                  ]
                },
                "m_groupUuids": null,
                "m_tenantId": "ABC0123"
              }
            ],
            "items": {},
            "type": "array"
          },
          "success": {
            "example": true,
            "type": "boolean"
          }
        },
        "type": "object"
      },
      "ResetPasswordResponse": {
        "properties": {
          "ErrorCode": {
            "example": null,
            "type": "string"
          },
          "ErrorID": {
            "example": null,
            "type": "string"
          },
          "Exception": {
            "example": null,
            "type": "string"
          },
          "InnerExceptions": {
            "example": null,
            "type": "string"
          },
          "IsSoftError": {
            "example": false,
            "type": "boolean"
          },
          "Message": {
            "example": null,
            "type": "string"
          },
          "MessageID": {
            "example": null,
            "type": "string"
          },
          "Result": {
            "example": 0,
            "type": "integer"
          },
          "success": {
            "example": true,
            "type": "boolean"
          }
        },
        "type": "object"
      },
      "UpdateUserResponse": {
        "properties": {
          "ErrorCode": {
            "example": null,
            "type": "string"
          },
          "ErrorID": {
            "example": null,
            "type": "string"
          },
          "Exception": {
            "example": null,
            "type": "string"
          },
          "InnerExceptions": {
            "example": null,
            "type": "string"
          },
          "IsSoftError": {
            "example": false,
            "type": "boolean"
          },
          "Message": {
            "example": null,
            "type": "string"
          },
          "MessageID": {
            "example": null,
            "type": "string"
          },
          "Result": {
            "example": {
              "ADUserId": "eecbcd1b-7905-4242-8250-7a63e6a4d1c7",
              "ChangedProperties": [
                {
                  "NewValues": [
                    "Test"
                  ],
                  "OldValues": null,
                  "PropertyName": "sn"
                }
              ],
              "ErrorMessage": "",
              "ExceptionString": null,
              "MemberOfAllGroups": [
                null
              ],
              "PasswordNeedToBeChanged": false,
              "RequestId": "3c818e399a18402096864c055f1982d7",
              "Status": 2,
              "Substatus": 26,
              "TempPasswordSet": false,
              "UserAccountControlAction": 0,
              "UserDn": "CN=testUser2,CN=Users,DC=CLOUDDEV,DC=TEST\""
            },
            "type": "object"
          },
          "success": {
            "example": true,
            "type": "boolean"
          }
        },
        "type": "object"
      },
      "ValidatePasswordResponse": {
        "properties": {
          "ErrorCode": {
            "example": null,
            "type": "string"
          },
          "ErrorID": {
            "example": null,
            "type": "string"
          },
          "Exception": {
            "example": null,
            "type": "string"
          },
          "InnerExceptions": {
            "example": null,
            "type": "string"
          },
          "IsSoftError": {
            "example": false,
            "type": "boolean"
          },
          "Message": {
            "example": null,
            "type": "string"
          },
          "MessageID": {
            "example": null,
            "type": "string"
          },
          "Result": {
            "example": true,
            "type": "boolean"
          },
          "success": {
            "example": true,
            "type": "boolean"
          }
        },
        "type": "object"
      },
      "assigngroupspayload": {
        "properties": {
          "ContainerDn": {
            "example": "05a9e2a7-206d-4ada-ad1a-f7240a472af8",
            "type": "string"
          },
          "DirectoryId": {
            "example": "05a9e2a7-206d-4ada-ad1a-f7240a472af8",
            "type": "string"
          },
          "Domain": {
            "example": "testTEST1234",
            "type": "string"
          },
          "GroupIds": {
            "example": [
              "group1ID",
              "group2ID"
            ],
            "items": {
              "type": "string"
            },
            "type": "array"
          },
          "Server": {
            "example": "05a9e2a7-206d-4ada-ad1a-f7240a472af8",
            "type": "string"
          },
          "userId": {
            "example": "testTEST1234",
            "type": "string"
          }
        },
        "title": "EntityResetpasswordRequest",
        "type": "object"
      },
      "unassigngroupspayload": {
        "properties": {
          "ContainerDn": {
            "example": "05a9e2a7-206d-4ada-ad1a-f7240a472af8",
            "type": "string"
          },
          "DirectoryId": {
            "example": "05a9e2a7-206d-4ada-ad1a-f7240a472af8",
            "type": "string"
          },
          "Domain": {
            "example": "testTEST1234",
            "type": "string"
          },
          "GroupIds": {
            "example": [
              "group1ID",
              "group2ID"
            ],
            "items": {
              "type": "string"
            },
            "type": "array"
          },
          "Server": {
            "example": "05a9e2a7-206d-4ada-ad1a-f7240a472af8",
            "type": "string"
          },
          "userId": {
            "example": "testTEST1234",
            "type": "string"
          }
        },
        "title": "EntityResetpasswordRequest",
        "type": "object"
      }
    },
    "security": []
  }